#!/usr/bin/env python3
"""Compare desktop and Android slicer G-code semantically for Alloy G3.

Inputs may be plain .gcode or Bambu/Orca .gcode.3mf archives. For archives the
first Metadata/plate_*.gcode member is used unless --plate-member is supplied.

The comparator intentionally ignores volatile metadata and does not require
byte-for-byte output. It compares:
- ordered feature-type transitions;
- layer count / Z progression;
- extrusion and travel move counts;
- approximate positive extrusion distance;
- reported print time and filament usage when both sides expose them.

G3 requires reported print time and filament use within 2% when available, and
no missing major toolpath feature classes. The report records unavailable
metrics rather than inventing them.
"""

from __future__ import annotations

import argparse
from collections import Counter
from dataclasses import asdict, dataclass
import json
from pathlib import Path
import re
from typing import Iterable
from zipfile import ZipFile

FLOAT = r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?"
TOKEN_RE = re.compile(r"([A-Za-z])(" + FLOAT + r")")
M204_RE = re.compile(r"^M204(?:\s+(.+?))?(?:\s*;.*)?$", re.I)

# Common Orca/Bambu/Prusa feature annotations. Keep this conservative: unknown
# comments are ignored instead of guessed into a feature class.
FEATURE_PATTERNS = [
    re.compile(r"^;\s*TYPE\s*:\s*(.+?)\s*$", re.I),
    re.compile(r"^;\s*FEATURE\s*:\s*(.+?)\s*$", re.I),
    re.compile(r"^;\s*LINE_TYPE\s*:\s*(.+?)\s*$", re.I),
]

MODEL_TIME_PATTERNS = [
    re.compile(r"model printing time.*?(?:=|:)\s*([^;]+)", re.I),
]
TOTAL_TIME_PATTERNS = [
    re.compile(r"total estimated time.*?(?:=|:)\s*([^;]+)", re.I),
]
TIME_PATTERNS = [
    re.compile(r"estimated printing time.*?(?:=|:)\s*([^;]+)", re.I),
]
FILAMENT_MM_PATTERNS = [
    re.compile(r"filament used(?!\s+for wipe tower) \[mm\].*?(?:=|:)\s*(.+)", re.I),
    re.compile(r"total filament used(?!\s+for wipe tower).*?\[mm\].*?(?:=|:)\s*(.+)", re.I),
    re.compile(r"total filament length \[mm\].*?(?:=|:)\s*(.+)", re.I),
]
FILAMENT_G_PATTERNS = [
    re.compile(r"filament used(?!\s+for wipe tower) \[g\].*?(?:=|:)\s*(.+)", re.I),
    re.compile(r"total filament used(?!\s+for wipe tower).*?\[g\].*?(?:=|:)\s*(.+)", re.I),
    re.compile(r"total filament weight \[g\].*?(?:=|:)\s*(.+)", re.I),
]

DECLARED_LAYER_RE = re.compile(r"total layer number\s*:\s*(\d+)", re.I)
LAYER_MARKER_RE = re.compile(r"^;\s*LAYER\s*:\s*(-?\d+)\s*$", re.I)
CHANGE_LAYER_RE = re.compile(r"^;\s*CHANGE_LAYER\b", re.I)

VOLATILE_PREFIXES = (
    "; generated by ",
    "; generated at ",
    "; creation_date",
    "; timestamp",
)


@dataclass
class Metrics:
    source: str
    archive_member: str | None
    line_count: int
    layer_count: int
    z_levels: list[float]
    extrusion_moves: int
    travel_moves: int
    positive_e_mm: float
    feature_transitions: list[str]
    feature_counts: dict[str, int]
    print_time_seconds: float | None
    filament_mm: float | None
    filament_g: float | None


def read_gcode(path: Path, plate_member: str | None) -> tuple[str, str | None]:
    lower = path.name.lower()
    if lower.endswith(".3mf") or lower.endswith(".zip"):
        with ZipFile(path) as zf:
            names = zf.namelist()
            if plate_member:
                if plate_member not in names:
                    raise SystemExit(f"Archive member not found: {plate_member}")
                member = plate_member
            else:
                candidates = sorted(
                    n for n in names
                    if re.fullmatch(r"Metadata/plate_\d+\.gcode", n, re.I)
                )
                if not candidates:
                    candidates = sorted(n for n in names if n.lower().endswith(".gcode"))
                if not candidates:
                    raise SystemExit(f"No .gcode member found in {path}")
                member = candidates[0]
            return zf.read(member).decode("utf-8", errors="replace"), member
    return path.read_text(errors="replace"), None


def parse_duration(value: str) -> float | None:
    s = value.strip().lower()
    # Orca/Prusa comments commonly use 1d 2h 3m 4s. Also accept HH:MM:SS.
    if re.fullmatch(r"\d+(?::\d+){1,2}", s):
        parts = [int(x) for x in s.split(":")]
        if len(parts) == 2:
            return float(parts[0] * 60 + parts[1])
        return float(parts[0] * 3600 + parts[1] * 60 + parts[2])
    total = 0.0
    found = False
    for amount, unit in re.findall(r"(" + FLOAT + r")\s*([dhms])", s):
        found = True
        factor = {"d": 86400, "h": 3600, "m": 60, "s": 1}[unit]
        total += float(amount) * factor
    return total if found else None


def parse_number_list(value: str) -> float | None:
    nums = re.findall(FLOAT, value)
    return sum(float(x) for x in nums) if nums else None


def last_matching(lines: Iterable[str], patterns: list[re.Pattern[str]], parser) -> float | None:
    result = None
    for line in lines:
        for pattern in patterns:
            m = pattern.search(line)
            if m:
                parsed = parser(m.group(1))
                if parsed is not None:
                    result = parsed
    return result


def canonical_feature(raw: str) -> str:
    value = re.sub(r"\s+", " ", raw.strip()).lower()
    aliases = {
        "outer wall": "outer_wall",
        "external perimeter": "outer_wall",
        "inner wall": "inner_wall",
        "perimeter": "inner_wall",
        "sparse infill": "sparse_infill",
        "internal infill": "sparse_infill",
        "solid infill": "solid_infill",
        "internal solid infill": "solid_infill",
        "top surface": "top_surface",
        "top solid infill": "top_surface",
        "bottom surface": "bottom_surface",
        "support": "support",
        "support material": "support",
        "support interface": "support_interface",
        "support material interface": "support_interface",
        "bridge": "bridge",
        "bridge infill": "bridge",
        "overhang wall": "overhang_wall",
        "overhang perimeter": "overhang_wall",
        "gap infill": "gap_fill",
        "skirt": "skirt",
        "skirt/brim": "skirt",
        "brim": "skirt",
        "prime tower": "prime_tower",
        "wipe tower": "prime_tower",
    }
    return aliases.get(value, value.replace(" ", "_"))


def declared_layer_count(lines: Iterable[str], fallback: int) -> int:
    """Return the slicer's declared layer count when it has one.

    Bambu writes an authoritative ``total layer number`` header. SliceBeam
    writes numbered ``;LAYER:n`` comments starting at one, while the small
    unit fixtures and the fallback emitter use Z moves. This keeps startup
    positioning moves out of the parity metric without pretending that every
    slicer uses the same comment spelling.
    """
    for line in lines:
        match = DECLARED_LAYER_RE.search(line)
        if match:
            return int(match.group(1))

    markers = [int(match.group(1)) for line in lines
               if (match := LAYER_MARKER_RE.match(line.strip()))]
    if markers:
        unique = set(markers)
        # Both zero-based and one-based slicers describe the highest layer
        # number, so the number of layers is still max+1. Do not count a
        # missing/duplicated marker as a new layer.
        if min(unique) >= 0:
            return max(unique) + 1
        return len(unique)

    change_layers = sum(1 for line in lines if CHANGE_LAYER_RE.match(line.strip()))
    return change_layers if change_layers else fallback


def feature_from_comment(line: str) -> str | None:
    for pattern in FEATURE_PATTERNS:
        m = pattern.match(line)
        if m:
            return canonical_feature(m.group(1))
    return None


# Different slicer families use different labels for the same geometric role.
# These are deliberately reported as aliases in the JSON instead of silently
# being folded into canonical_feature(), so a reviewer can see where the
# engines made a semantic rather than textual match.
FEATURE_ROLE_ALIASES = {
    "bottom_surface": ("solid_infill",),
    "floating_vertical_shell": ("outer_wall",),
    "inner_wall": ("gap_fill",),
    # Bambu labels this sparse roof-repair role `Bridge`; the pinned
    # Orca/Prusa writer labels the same deposited path `Internal bridge`.
    # Keep it visible as an alias so the report distinguishes nomenclature
    # from a genuinely missing bridge toolpath.
    "bridge": ("internal_bridge",),
}


def parse_metrics(path: Path, plate_member: str | None) -> Metrics:
    text, member = read_gcode(path, plate_member)
    lines = text.splitlines()

    feature_transitions: list[str] = []
    feature_counts: Counter[str] = Counter()
    z_levels: list[float] = []
    seen_z: set[float] = set()
    extrusion_moves = 0
    travel_moves = 0
    positive_e_mm = 0.0

    xyz = {"X": 0.0, "Y": 0.0, "Z": 0.0}
    e_value = 0.0
    absolute_xyz = True
    absolute_e = True

    for raw_line in lines:
        line = raw_line.strip()
        if not line:
            continue
        lower = line.lower()
        if lower.startswith(VOLATILE_PREFIXES):
            continue

        feature = feature_from_comment(line)
        if feature is not None:
            feature_counts[feature] += 1
            if not feature_transitions or feature_transitions[-1] != feature:
                feature_transitions.append(feature)
            continue

        code = line.split(";", 1)[0].strip()
        if not code:
            continue
        command = code.split(maxsplit=1)[0].upper()
        if command == "G90":
            absolute_xyz = True
            continue
        if command == "G91":
            absolute_xyz = False
            continue
        if command == "M82":
            absolute_e = True
            continue
        if command == "M83":
            absolute_e = False
            continue
        if command == "G92":
            vals = {k.upper(): float(v) for k, v in TOKEN_RE.findall(code)}
            if "E" in vals:
                e_value = vals["E"]
            for axis in "XYZ":
                if axis in vals:
                    xyz[axis] = vals[axis]
            continue
        if command not in {"G0", "G1", "G2", "G3"}:
            continue

        vals = {k.upper(): float(v) for k, v in TOKEN_RE.findall(code)}
        moved_xyz = any(k in vals for k in "XYZ")

        if "Z" in vals:
            new_z = vals["Z"] if absolute_xyz else xyz["Z"] + vals["Z"]
            rounded = round(new_z, 5)
            if rounded not in seen_z:
                seen_z.add(rounded)
                z_levels.append(rounded)
            xyz["Z"] = new_z
        for axis in "XY":
            if axis in vals:
                xyz[axis] = vals[axis] if absolute_xyz else xyz[axis] + vals[axis]

        positive_e = 0.0
        if "E" in vals:
            if absolute_e:
                delta = vals["E"] - e_value
                e_value = vals["E"]
            else:
                delta = vals["E"]
                e_value += delta
            if delta > 0:
                positive_e = delta
                positive_e_mm += delta

        if positive_e > 0:
            extrusion_moves += 1
        elif moved_xyz:
            travel_moves += 1

    # Bambu's total estimate includes machine warm-up and other orchestration
    # time that the native slicer does not report. Prefer model time when it is
    # available; retain total time as a diagnostic fallback only.
    print_time = last_matching(lines, MODEL_TIME_PATTERNS, parse_duration)
    if print_time is None:
        print_time = last_matching(lines, TIME_PATTERNS, parse_duration)
    if print_time is None:
        print_time = last_matching(lines, TOTAL_TIME_PATTERNS, parse_duration)
    filament_mm = last_matching(lines, FILAMENT_MM_PATTERNS, parse_number_list)
    filament_g = last_matching(lines, FILAMENT_G_PATTERNS, parse_number_list)

    return Metrics(
        source=str(path),
        archive_member=member,
        line_count=len(lines),
        layer_count=declared_layer_count(lines, len(z_levels)),
        z_levels=z_levels,
        extrusion_moves=extrusion_moves,
        travel_moves=travel_moves,
        positive_e_mm=positive_e_mm,
        feature_transitions=feature_transitions,
        feature_counts=dict(feature_counts),
        print_time_seconds=print_time,
        filament_mm=filament_mm,
        filament_g=filament_g,
    )


def acceleration_signature(path: Path, plate_member: str | None) -> list[tuple[str, float]]:
    """Return the ordered acceleration intent emitted by each slicer.

    Orca/Bambu commonly encode the print acceleration with ``M204 S`` while
    SliceBeam uses ``M204 P``. Treat those spellings as the same canonical
    print-acceleration channel, but preserve travel/retract channels so a
    genuinely different motion policy remains visible in the report.
    """
    text, _ = read_gcode(path, plate_member)
    signature: list[tuple[str, float]] = []
    for raw_line in text.splitlines():
        match = M204_RE.match(raw_line.strip())
        if not match:
            continue
        values = {key.upper(): float(value) for key, value in TOKEN_RE.findall(match.group(1) or "")}
        for key, value in values.items():
            canonical = "P" if key in {"S", "P"} else key
            signature.append((canonical, value))
    return signature


def first_acceleration_mismatch(desktop: list[tuple[str, float]],
                                android: list[tuple[str, float]]) -> str:
    """Describe the first normalized acceleration command that diverges."""
    limit = min(len(desktop), len(android))
    for index in range(limit):
        if desktop[index] != android[index]:
            return f"index={index}, desktop={desktop[index][0]}{desktop[index][1]:g}, Android={android[index][0]}{android[index][1]:g}"
    if len(desktop) != len(android):
        return f"sequence length desktop={len(desktop)}, Android={len(android)}"
    return "none"


def relative_diff(a: float, b: float) -> float:
    denom = max(abs(a), abs(b), 1e-12)
    return abs(a - b) / denom


def compare(desktop: Metrics, android: Metrics, tolerance: float,
            profile_identity: dict | None = None) -> dict:
    checks: list[dict] = []

    def add(name: str, status: str, detail: str) -> None:
        checks.append({"name": name, "status": status, "detail": detail})

    # Major feature classes: Android must not omit anything desktop reports.
    # First account for explicitly documented cross-slicer role aliases, then
    # keep genuinely uncovered classes as a hard failure.
    desktop_features = set(desktop.feature_counts)
    android_features = set(android.feature_counts)
    direct_missing = desktop_features - android_features
    equivalent: dict[str, list[str]] = {}
    missing = []
    for feature in sorted(direct_missing):
        aliases = [alias for alias in FEATURE_ROLE_ALIASES.get(feature, ())
                   if alias in android_features]
        if aliases:
            equivalent[feature] = aliases
        else:
            missing.append(feature)
    add(
        "major_feature_classes",
        "pass" if not missing else "fail",
        "none missing" if not missing else "missing on Android: " + ", ".join(missing),
    )
    if profile_identity is not None:
        profile_result = profile_identity.get("result")
        failed_fields = profile_identity.get("failed_fields", [])
        add(
            "profile_identity",
            "pass" if profile_result == "pass" else "fail",
            f"{profile_identity.get('checked_fields', 0)} source-backed fields match" if profile_result == "pass" else
            "profile mismatch: " + ", ".join(str(field) for field in failed_fields),
        )
    add(
        "semantic_feature_aliases",
        "pass" if equivalent else "unavailable",
        "none" if not equivalent else "; ".join(
            f"{source} covered by {', '.join(targets)}"
            for source, targets in sorted(equivalent.items())
        ),
    )

    # Exact transition order is useful evidence but overly strict across harmless emitter changes.
    # Record it as pass/warn, while missing feature classes is the hard failure above.
    if desktop.feature_transitions == android.feature_transitions:
        add("feature_transition_sequence", "pass", "exact canonical transition sequence match")
    else:
        add(
            "feature_transition_sequence",
            "warn",
            f"desktop transitions={len(desktop.feature_transitions)}, Android={len(android.feature_transitions)}; inspect visual diff",
        )

    layer_diff = abs(desktop.layer_count - android.layer_count)
    add(
        "layer_count",
        "pass" if layer_diff == 0 else "fail",
        f"desktop={desktop.layer_count}, Android={android.layer_count}",
    )

    for name in ("print_time_seconds", "filament_mm", "filament_g"):
        a = getattr(desktop, name)
        b = getattr(android, name)
        if a is None or b is None:
            add(name, "unavailable", f"desktop={a}, Android={b}")
            continue
        diff = relative_diff(a, b)
        add(
            name,
            "pass" if diff <= tolerance else "fail",
            f"desktop={a:.6g}, Android={b:.6g}, delta={diff:.2%}, tolerance={tolerance:.2%}",
        )

    # Motion/extrusion metrics are diagnostics. A slight emitter variation is allowed, but
    # large divergence is a hard warning requiring toolpath inspection.
    for name in ("extrusion_moves", "travel_moves", "positive_e_mm"):
        a = float(getattr(desktop, name))
        b = float(getattr(android, name))
        diff = relative_diff(a, b)
        add(
            name,
            "pass" if diff <= 0.05 else "warn",
            f"desktop={a:.6g}, Android={b:.6g}, delta={diff:.2%}",
        )

    desktop_acceleration = acceleration_signature(Path(desktop.source), desktop.archive_member)
    android_acceleration = acceleration_signature(Path(android.source), android.archive_member)
    if not desktop_acceleration or not android_acceleration:
        add(
            "acceleration_command_profile",
            "unavailable",
            f"desktop commands={len(desktop_acceleration)}, Android={len(android_acceleration)}",
        )
    elif desktop_acceleration == android_acceleration:
        add(
            "acceleration_command_profile",
            "pass",
            "ordered normalized M204 command sequence matches",
        )
    else:
        add(
            "acceleration_command_profile",
            "warn",
            "normalized M204 sequence differs: "
            + first_acceleration_mismatch(desktop_acceleration, android_acceleration),
        )

    hard_fail = any(c["status"] == "fail" for c in checks)
    # G3 cannot pass if neither filament representation nor print time is available from both.
    time_check = next(c for c in checks if c["name"] == "print_time_seconds")
    filament_checks = [c for c in checks if c["name"] in {"filament_mm", "filament_g"}]
    evidence_complete = (
        time_check["status"] != "unavailable"
        and any(c["status"] != "unavailable" for c in filament_checks)
    )
    return {
        "tolerance": tolerance,
        "profile_identity": profile_identity,
        "checks": checks,
        "evidence_complete": evidence_complete,
        "result": "pass" if not hard_fail and evidence_complete else "fail",
    }


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("desktop", type=Path)
    p.add_argument("android", type=Path)
    p.add_argument("--plate-member")
    p.add_argument("--tolerance", type=float, default=0.02)
    p.add_argument("--desktop-profile", type=Path,
                   help="Bambu .gcode.3mf, resolved G-code, or project settings JSON used for the slice")
    p.add_argument("--desktop-profile-overlay", type=Path, action="append", default=[],
                   help="explicit Bambu project/object override JSON/3MF; repeatable")
    p.add_argument("--native-config", type=Path,
                   help="native config.ini used for the Android slice")
    p.add_argument("--json-out", type=Path)
    args = p.parse_args()

    if (args.desktop_profile is None) != (args.native_config is None):
        p.error("--desktop-profile and --native-config must be supplied together")

    desktop = parse_metrics(args.desktop, args.plate_member)
    android = parse_metrics(args.android, args.plate_member)
    profile_identity = None
    if args.desktop_profile is not None:
        # Keep the import local so the comparator remains usable as a small
        # standalone metrics library in environments that only need G-code.
        from verify_g3_profile import merged_desktop_settings, read_native_settings, verify
        profile_identity = verify(
            merged_desktop_settings(args.desktop_profile, args.desktop_profile_overlay),
            read_native_settings(args.native_config),
        )
    comparison = compare(desktop, android, args.tolerance, profile_identity)
    report = {
        "desktop": asdict(desktop),
        "android": asdict(android),
        "comparison": comparison,
    }

    rendered = json.dumps(report, indent=2)
    if args.json_out:
        args.json_out.parent.mkdir(parents=True, exist_ok=True)
        args.json_out.write_text(rendered + "\n")
    print(rendered)
    raise SystemExit(0 if comparison["result"] == "pass" else 2)


if __name__ == "__main__":
    main()
