#!/usr/bin/env python3
"""Compare desktop and Android slicer G-code semantically for Alloy G3.

Inputs may be plain .gcode or Bambu/Orca .gcode.3mf archives. For archives the
first Metadata/plate_*.gcode member is used unless --plate-member is supplied.

The comparator intentionally ignores volatile metadata and does not require
byte-for-byte output. It compares:
- ordered feature-type transitions;
- layer count / Z progression;
- extrusion and travel move counts;
- approximate positive extrusion distance;
- reported print time and filament usage when both sides expose them.

G3 requires reported print time and filament use within 2% when available, and
no missing major toolpath feature classes. The report records unavailable
metrics rather than inventing them.
"""

from __future__ import annotations

import argparse
from collections import Counter
from dataclasses import asdict, dataclass
import json
from pathlib import Path
import re
from typing import Iterable
from zipfile import ZipFile

FLOAT = r"[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?"
TOKEN_RE = re.compile(r"([A-Za-z])(" + FLOAT + r")")

# Common Orca/Bambu/Prusa feature annotations. Keep this conservative: unknown
# comments are ignored instead of guessed into a feature class.
FEATURE_PATTERNS = [
    re.compile(r"^;\s*TYPE\s*:\s*(.+?)\s*$", re.I),
    re.compile(r"^;\s*FEATURE\s*:\s*(.+?)\s*$", re.I),
    re.compile(r"^;\s*LINE_TYPE\s*:\s*(.+?)\s*$", re.I),
]

TIME_PATTERNS = [
    re.compile(r"estimated printing time.*?=\s*([^;]+)", re.I),
    re.compile(r"total estimated time.*?=\s*([^;]+)", re.I),
    re.compile(r"model printing time.*?=\s*([^;]+)", re.I),
]
FILAMENT_MM_PATTERNS = [
    re.compile(r"filament used \[mm\]\s*=\s*(.+)", re.I),
    re.compile(r"total filament used.*?\[mm\]\s*=\s*(.+)", re.I),
]
FILAMENT_G_PATTERNS = [
    re.compile(r"filament used \[g\]\s*=\s*(.+)", re.I),
    re.compile(r"total filament used.*?\[g\]\s*=\s*(.+)", re.I),
]

VOLATILE_PREFIXES = (
    "; generated by ",
    "; generated at ",
    "; creation_date",
    "; timestamp",
)


@dataclass
class Metrics:
    source: str
    archive_member: str | None
    line_count: int
    layer_count: int
    z_levels: list[float]
    extrusion_moves: int
    travel_moves: int
    positive_e_mm: float
    feature_transitions: list[str]
    feature_counts: dict[str, int]
    print_time_seconds: float | None
    filament_mm: float | None
    filament_g: float | None


def read_gcode(path: Path, plate_member: str | None) -> tuple[str, str | None]:
    lower = path.name.lower()
    if lower.endswith(".3mf") or lower.endswith(".zip"):
        with ZipFile(path) as zf:
            names = zf.namelist()
            if plate_member:
                if plate_member not in names:
                    raise SystemExit(f"Archive member not found: {plate_member}")
                member = plate_member
            else:
                candidates = sorted(
                    n for n in names
                    if re.fullmatch(r"Metadata/plate_\d+\.gcode", n, re.I)
                )
                if not candidates:
                    candidates = sorted(n for n in names if n.lower().endswith(".gcode"))
                if not candidates:
                    raise SystemExit(f"No .gcode member found in {path}")
                member = candidates[0]
            return zf.read(member).decode("utf-8", errors="replace"), member
    return path.read_text(errors="replace"), None


def parse_duration(value: str) -> float | None:
    s = value.strip().lower()
    # Orca/Prusa comments commonly use 1d 2h 3m 4s. Also accept HH:MM:SS.
    if re.fullmatch(r"\d+(?::\d+){1,2}", s):
        parts = [int(x) for x in s.split(":")]
        if len(parts) == 2:
            return float(parts[0] * 60 + parts[1])
        return float(parts[0] * 3600 + parts[1] * 60 + parts[2])
    total = 0.0
    found = False
    for amount, unit in re.findall(r"(" + FLOAT + r")\s*([dhms])", s):
        found = True
        factor = {"d": 86400, "h": 3600, "m": 60, "s": 1}[unit]
        total += float(amount) * factor
    return total if found else None


def parse_number_list(value: str) -> float | None:
    nums = re.findall(FLOAT, value)
    return sum(float(x) for x in nums) if nums else None


def last_matching(lines: Iterable[str], patterns: list[re.Pattern[str]], parser) -> float | None:
    result = None
    for line in lines:
        for pattern in patterns:
            m = pattern.search(line)
            if m:
                parsed = parser(m.group(1))
                if parsed is not None:
                    result = parsed
    return result


def canonical_feature(raw: str) -> str:
    value = re.sub(r"\s+", " ", raw.strip()).lower()
    aliases = {
        "outer wall": "outer_wall",
        "external perimeter": "outer_wall",
        "inner wall": "inner_wall",
        "perimeter": "inner_wall",
        "sparse infill": "sparse_infill",
        "internal infill": "sparse_infill",
        "solid infill": "solid_infill",
        "internal solid infill": "solid_infill",
        "top surface": "top_surface",
        "top solid infill": "top_surface",
        "bottom surface": "bottom_surface",
        "support": "support",
        "support interface": "support_interface",
        "bridge": "bridge",
        "overhang wall": "overhang_wall",
        "skirt": "skirt",
        "brim": "brim",
        "prime tower": "prime_tower",
        "wipe tower": "prime_tower",
    }
    return aliases.get(value, value.replace(" ", "_"))


def feature_from_comment(line: str) -> str | None:
    for pattern in FEATURE_PATTERNS:
        m = pattern.match(line)
        if m:
            return canonical_feature(m.group(1))
    return None


def parse_metrics(path: Path, plate_member: str | None) -> Metrics:
    text, member = read_gcode(path, plate_member)
    lines = text.splitlines()

    feature_transitions: list[str] = []
    feature_counts: Counter[str] = Counter()
    z_levels: list[float] = []
    seen_z: set[float] = set()
    extrusion_moves = 0
    travel_moves = 0
    positive_e_mm = 0.0

    xyz = {"X": 0.0, "Y": 0.0, "Z": 0.0}
    e_value = 0.0
    absolute_xyz = True
    absolute_e = True

    for raw_line in lines:
        line = raw_line.strip()
        if not line:
            continue
        lower = line.lower()
        if lower.startswith(VOLATILE_PREFIXES):
            continue

        feature = feature_from_comment(line)
        if feature is not None:
            feature_counts[feature] += 1
            if not feature_transitions or feature_transitions[-1] != feature:
                feature_transitions.append(feature)
            continue

        code = line.split(";", 1)[0].strip()
        if not code:
            continue
        command = code.split(maxsplit=1)[0].upper()
        if command == "G90":
            absolute_xyz = True
            continue
        if command == "G91":
            absolute_xyz = False
            continue
        if command == "M82":
            absolute_e = True
            continue
        if command == "M83":
            absolute_e = False
            continue
        if command == "G92":
            vals = {k.upper(): float(v) for k, v in TOKEN_RE.findall(code)}
            if "E" in vals:
                e_value = vals["E"]
            for axis in "XYZ":
                if axis in vals:
                    xyz[axis] = vals[axis]
            continue
        if command not in {"G0", "G1", "G2", "G3"}:
            continue

        vals = {k.upper(): float(v) for k, v in TOKEN_RE.findall(code)}
        moved_xyz = any(k in vals for k in "XYZ")

        if "Z" in vals:
            new_z = vals["Z"] if absolute_xyz else xyz["Z"] + vals["Z"]
            rounded = round(new_z, 5)
            if rounded not in seen_z:
                seen_z.add(rounded)
                z_levels.append(rounded)
            xyz["Z"] = new_z
        for axis in "XY":
            if axis in vals:
                xyz[axis] = vals[axis] if absolute_xyz else xyz[axis] + vals[axis]

        positive_e = 0.0
        if "E" in vals:
            if absolute_e:
                delta = vals["E"] - e_value
                e_value = vals["E"]
            else:
                delta = vals["E"]
                e_value += delta
            if delta > 0:
                positive_e = delta
                positive_e_mm += delta

        if positive_e > 0:
            extrusion_moves += 1
        elif moved_xyz:
            travel_moves += 1

    print_time = last_matching(lines, TIME_PATTERNS, parse_duration)
    filament_mm = last_matching(lines, FILAMENT_MM_PATTERNS, parse_number_list)
    filament_g = last_matching(lines, FILAMENT_G_PATTERNS, parse_number_list)

    return Metrics(
        source=str(path),
        archive_member=member,
        line_count=len(lines),
        layer_count=len(z_levels),
        z_levels=z_levels,
        extrusion_moves=extrusion_moves,
        travel_moves=travel_moves,
        positive_e_mm=positive_e_mm,
        feature_transitions=feature_transitions,
        feature_counts=dict(feature_counts),
        print_time_seconds=print_time,
        filament_mm=filament_mm,
        filament_g=filament_g,
    )


def relative_diff(a: float, b: float) -> float:
    denom = max(abs(a), abs(b), 1e-12)
    return abs(a - b) / denom


def compare(desktop: Metrics, android: Metrics, tolerance: float) -> dict:
    checks: list[dict] = []

    def add(name: str, status: str, detail: str) -> None:
        checks.append({"name": name, "status": status, "detail": detail})

    # Major feature classes: Android must not omit anything desktop reports.
    desktop_features = set(desktop.feature_counts)
    android_features = set(android.feature_counts)
    missing = sorted(desktop_features - android_features)
    add(
        "major_feature_classes",
        "pass" if not missing else "fail",
        "none missing" if not missing else "missing on Android: " + ", ".join(missing),
    )

    # Exact transition order is useful evidence but overly strict across harmless emitter changes.
    # Record it as pass/warn, while missing feature classes is the hard failure above.
    if desktop.feature_transitions == android.feature_transitions:
        add("feature_transition_sequence", "pass", "exact canonical transition sequence match")
    else:
        add(
            "feature_transition_sequence",
            "warn",
            f"desktop transitions={len(desktop.feature_transitions)}, Android={len(android.feature_transitions)}; inspect visual diff",
        )

    layer_diff = abs(desktop.layer_count - android.layer_count)
    add(
        "layer_count",
        "pass" if layer_diff == 0 else "fail",
        f"desktop={desktop.layer_count}, Android={android.layer_count}",
    )

    for name in ("print_time_seconds", "filament_mm", "filament_g"):
        a = getattr(desktop, name)
        b = getattr(android, name)
        if a is None or b is None:
            add(name, "unavailable", f"desktop={a}, Android={b}")
            continue
        diff = relative_diff(a, b)
        add(
            name,
            "pass" if diff <= tolerance else "fail",
            f"desktop={a:.6g}, Android={b:.6g}, delta={diff:.2%}, tolerance={tolerance:.2%}",
        )

    # Motion/extrusion metrics are diagnostics. A slight emitter variation is allowed, but
    # large divergence is a hard warning requiring toolpath inspection.
    for name in ("extrusion_moves", "travel_moves", "positive_e_mm"):
        a = float(getattr(desktop, name))
        b = float(getattr(android, name))
        diff = relative_diff(a, b)
        add(
            name,
            "pass" if diff <= 0.05 else "warn",
            f"desktop={a:.6g}, Android={b:.6g}, delta={diff:.2%}",
        )

    hard_fail = any(c["status"] == "fail" for c in checks)
    # G3 cannot pass if neither filament representation nor print time is available from both.
    time_check = next(c for c in checks if c["name"] == "print_time_seconds")
    filament_checks = [c for c in checks if c["name"] in {"filament_mm", "filament_g"}]
    evidence_complete = (
        time_check["status"] != "unavailable"
        and any(c["status"] != "unavailable" for c in filament_checks)
    )
    return {
        "tolerance": tolerance,
        "checks": checks,
        "evidence_complete": evidence_complete,
        "result": "pass" if not hard_fail and evidence_complete else "fail",
    }


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("desktop", type=Path)
    p.add_argument("android", type=Path)
    p.add_argument("--plate-member")
    p.add_argument("--tolerance", type=float, default=0.02)
    p.add_argument("--json-out", type=Path)
    args = p.parse_args()

    desktop = parse_metrics(args.desktop, args.plate_member)
    android = parse_metrics(args.android, args.plate_member)
    comparison = compare(desktop, android, args.tolerance)
    report = {
        "desktop": asdict(desktop),
        "android": asdict(android),
        "comparison": comparison,
    }

    rendered = json.dumps(report, indent=2)
    if args.json_out:
        args.json_out.parent.mkdir(parents=True, exist_ok=True)
        args.json_out.write_text(rendered + "\n")
    print(rendered)
    raise SystemExit(0 if comparison["result"] == "pass" else 2)


if __name__ == "__main__":
    main()
