#!/usr/bin/env python3

from pathlib import Path
import tempfile
import unittest
from zipfile import ZipFile

from compare_gcode import compare, parse_metrics


GCODE_A = """; generated by OrcaSlicer
; estimated printing time (normal mode) = 1m 40s
; filament used [mm] = 1000.0
; filament used [g] = 3.00
G90
M82
G92 E0
G1 Z0.20 F600
;TYPE:Outer wall
G1 X10 Y0 E1.0
G1 X10 Y10 E2.0
;TYPE:Sparse infill
G1 X0 Y0 E3.0
G1 Z0.40
;TYPE:Outer wall
G1 X20 Y0 E4.0
"""

GCODE_B = """; generated by Android port
; estimated printing time (normal mode) = 1m 41s
; filament used [mm] = 1008.0
; filament used [g] = 3.02
G90
M82
G92 E0
G1 Z0.20 F600
; FEATURE: External perimeter
G1 X10 Y0 E1.0
G1 X10 Y10 E2.0
; FEATURE: Internal infill
G1 X0 Y0 E3.0
G1 Z0.40
; FEATURE: External perimeter
G1 X20 Y0 E4.0
"""

GCODE_MISSING_FEATURE = GCODE_B.replace("; FEATURE: Internal infill\n", "")

GCODE_ACCELERATION_EQUIVALENT = GCODE_A.replace("G90\n", "G90\nM204 S1500\nM204 S500\n")
GCODE_ACCELERATION_NATIVE = GCODE_B.replace("G90\n", "G90\nM204 P1500\nM204 P500\n")


class CompareGcodeTests(unittest.TestCase):
    def test_profile_identity_is_a_hard_check_when_attached(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            desktop = parse_metrics(self.write(root, "a.gcode", GCODE_A), None)
            android = parse_metrics(self.write(root, "b.gcode", GCODE_B), None)
            report = compare(
                desktop,
                android,
                0.02,
                {"result": "fail", "failed_fields": ["fill_density"]},
            )
            self.assertEqual("fail", report["result"])
            self.assertEqual("fail", next(
                check for check in report["checks"] if check["name"] == "profile_identity"
            )["status"])

    def write(self, root: Path, name: str, content: str) -> Path:
        path = root / name
        path.write_text(content)
        return path

    def test_plain_gcode_semantic_match_within_two_percent(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            a = parse_metrics(self.write(root, "a.gcode", GCODE_A), None)
            b = parse_metrics(self.write(root, "b.gcode", GCODE_B), None)
            result = compare(a, b, 0.02)
            self.assertEqual(result["result"], "pass")
            self.assertTrue(result["evidence_complete"])
            self.assertEqual(a.layer_count, 2)
            self.assertEqual(b.layer_count, 2)
            self.assertAlmostEqual(a.positive_e_mm, 4.0)
            self.assertAlmostEqual(b.positive_e_mm, 4.0)

    def test_missing_feature_is_hard_failure(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            a = parse_metrics(self.write(root, "a.gcode", GCODE_A), None)
            b = parse_metrics(self.write(root, "b.gcode", GCODE_MISSING_FEATURE), None)
            result = compare(a, b, 0.02)
            self.assertEqual(result["result"], "fail")
            feature = next(c for c in result["checks"] if c["name"] == "major_feature_classes")
            self.assertEqual(feature["status"], "fail")

    def test_acceleration_command_profile_normalizes_orca_s_and_native_p(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            desktop = parse_metrics(self.write(root, "desktop.gcode", GCODE_ACCELERATION_EQUIVALENT), None)
            android = parse_metrics(self.write(root, "android.gcode", GCODE_ACCELERATION_NATIVE), None)
            result = compare(desktop, android, 0.02)
            acceleration = next(c for c in result["checks"] if c["name"] == "acceleration_command_profile")
            self.assertEqual(acceleration["status"], "pass")

    def test_acceleration_command_profile_warns_on_motion_policy_change(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            desktop_text = GCODE_ACCELERATION_EQUIVALENT
            android_text = GCODE_ACCELERATION_NATIVE.replace("M204 P500", "M204 P700")
            desktop = parse_metrics(self.write(root, "desktop.gcode", desktop_text), None)
            android = parse_metrics(self.write(root, "android.gcode", android_text), None)
            result = compare(desktop, android, 0.02)
            acceleration = next(c for c in result["checks"] if c["name"] == "acceleration_command_profile")
            self.assertEqual(acceleration["status"], "warn")
            self.assertIn("desktop=P500, Android=P700", acceleration["detail"])

    def test_feature_transition_warning_identifies_first_divergence(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            desktop = parse_metrics(self.write(root, "desktop.gcode", GCODE_A), None)
            android_text = GCODE_B.replace(
                "; FEATURE: External perimeter\nG1 X20",
                "; FEATURE: Top surface\nG1 X20",
            )
            android = parse_metrics(self.write(root, "android.gcode", android_text), None)

            result = compare(desktop, android, tolerance=0.02)
            transition = next(
                c for c in result["checks"]
                if c["name"] == "feature_transition_sequence"
            )
            self.assertEqual(transition["status"], "warn")
            self.assertIn("index=2", transition["detail"])
            self.assertIn("desktop=outer_wall", transition["detail"])
            self.assertIn("Android=top_surface", transition["detail"])

    def test_internal_bridge_is_reported_as_bridge_alias(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            desktop = self.write(root, "desktop.gcode", GCODE_A + "; FEATURE: Bridge\n")
            android = self.write(root, "android.gcode", GCODE_A + ";TYPE:Internal Bridge\n")
            result = compare(parse_metrics(desktop, None), parse_metrics(android, None), 0.02)
            feature = next(c for c in result["checks"] if c["name"] == "major_feature_classes")
            self.assertEqual(feature["status"], "pass")
            aliases = next(c for c in result["checks"] if c["name"] == "semantic_feature_aliases")
            self.assertIn("bridge covered by internal_bridge", aliases["detail"])

    def test_reads_plate_gcode_from_3mf(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            archive = root / "fixture.gcode.3mf"
            with ZipFile(archive, "w") as zf:
                zf.writestr("Metadata/plate_1.gcode", GCODE_A)
                zf.writestr("Metadata/plate_1.png", b"not an image test")
            metrics = parse_metrics(archive, None)
            self.assertEqual(metrics.archive_member, "Metadata/plate_1.gcode")
            self.assertEqual(metrics.layer_count, 2)
            self.assertEqual(metrics.feature_counts["outer_wall"], 2)

    def test_relative_extrusion_mode(self):
        gcode = """; estimated printing time = 10s
; filament used [mm] = 2
G90
M83
G1 Z0.2
;TYPE:Outer wall
G1 X1 E0.5
G1 X2 E0.75
G1 X3 E-0.2
G1 X4 E0.75
"""
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            metrics = parse_metrics(self.write(root, "relative.gcode", gcode), None)
            self.assertAlmostEqual(metrics.positive_e_mm, 2.0)
            self.assertEqual(metrics.extrusion_moves, 3)

    def test_bambu_headers_and_slice_beam_layer_markers_are_normalized(self):
        bambu = """; model printing time: 28m 50s; total estimated time: 28m 51s
; total layer number: 100
; total filament length [mm] : 1257.28
; total filament weight [g] : 0.00
G90
G1 Z0.01
; CHANGE_LAYER
G1 Z0.20
"""
        slicebeam = """; estimated printing time = 28m 51s
; filament used [mm] = 1257.28
G90
;LAYER:0
G1 Z0.20
;LAYER:1
G1 Z0.40
"""
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            desktop = parse_metrics(self.write(root, "bambu.gcode", bambu), None)
            android = parse_metrics(self.write(root, "android.gcode", slicebeam), None)
            self.assertEqual(desktop.layer_count, 100)
            self.assertEqual(android.layer_count, 2)
            self.assertEqual(desktop.print_time_seconds, 1730.0)
            self.assertAlmostEqual(desktop.filament_mm, 1257.28)
            self.assertAlmostEqual(desktop.filament_g, 0.0)


if __name__ == "__main__":
    unittest.main()
