#!/usr/bin/env python3

from pathlib import Path
import tempfile
import unittest
from zipfile import ZipFile

from compare_gcode import compare, parse_metrics


GCODE_A = """; generated by OrcaSlicer
; estimated printing time (normal mode) = 1m 40s
; filament used [mm] = 1000.0
; filament used [g] = 3.00
G90
M82
G92 E0
G1 Z0.20 F600
;TYPE:Outer wall
G1 X10 Y0 E1.0
G1 X10 Y10 E2.0
;TYPE:Sparse infill
G1 X0 Y0 E3.0
G1 Z0.40
;TYPE:Outer wall
G1 X20 Y0 E4.0
"""

GCODE_B = """; generated by Android port
; estimated printing time (normal mode) = 1m 41s
; filament used [mm] = 1008.0
; filament used [g] = 3.02
G90
M82
G92 E0
G1 Z0.20 F600
; FEATURE: External perimeter
G1 X10 Y0 E1.0
G1 X10 Y10 E2.0
; FEATURE: Internal infill
G1 X0 Y0 E3.0
G1 Z0.40
; FEATURE: External perimeter
G1 X20 Y0 E4.0
"""

GCODE_MISSING_FEATURE = GCODE_B.replace("; FEATURE: Internal infill\n", "")


class CompareGcodeTests(unittest.TestCase):
    def write(self, root: Path, name: str, content: str) -> Path:
        path = root / name
        path.write_text(content)
        return path

    def test_plain_gcode_semantic_match_within_two_percent(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            a = parse_metrics(self.write(root, "a.gcode", GCODE_A), None)
            b = parse_metrics(self.write(root, "b.gcode", GCODE_B), None)
            result = compare(a, b, 0.02)
            self.assertEqual(result["result"], "pass")
            self.assertTrue(result["evidence_complete"])
            self.assertEqual(a.layer_count, 2)
            self.assertEqual(b.layer_count, 2)
            self.assertAlmostEqual(a.positive_e_mm, 4.0)
            self.assertAlmostEqual(b.positive_e_mm, 4.0)

    def test_missing_feature_is_hard_failure(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            a = parse_metrics(self.write(root, "a.gcode", GCODE_A), None)
            b = parse_metrics(self.write(root, "b.gcode", GCODE_MISSING_FEATURE), None)
            result = compare(a, b, 0.02)
            self.assertEqual(result["result"], "fail")
            feature = next(c for c in result["checks"] if c["name"] == "major_feature_classes")
            self.assertEqual(feature["status"], "fail")

    def test_reads_plate_gcode_from_3mf(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            archive = root / "fixture.gcode.3mf"
            with ZipFile(archive, "w") as zf:
                zf.writestr("Metadata/plate_1.gcode", GCODE_A)
                zf.writestr("Metadata/plate_1.png", b"not an image test")
            metrics = parse_metrics(archive, None)
            self.assertEqual(metrics.archive_member, "Metadata/plate_1.gcode")
            self.assertEqual(metrics.layer_count, 2)
            self.assertEqual(metrics.feature_counts["outer_wall"], 2)

    def test_relative_extrusion_mode(self):
        gcode = """; estimated printing time = 10s
; filament used [mm] = 2
G90
M83
G1 Z0.2
;TYPE:Outer wall
G1 X1 E0.5
G1 X2 E0.75
G1 X3 E-0.2
G1 X4 E0.75
"""
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            metrics = parse_metrics(self.write(root, "relative.gcode", gcode), None)
            self.assertAlmostEqual(metrics.positive_e_mm, 2.0)
            self.assertEqual(metrics.extrusion_moves, 3)


if __name__ == "__main__":
    unittest.main()
